### ISSUE TITLE
Error with Signals and Threads in Ruby 2.0

### ISSUE THREAD

**Issue by asenchi** [asenchi/scrolls#53]
Ran into this today, which is the [result of Ruby 2.0 changes](https://bugs.ruby-lang.org/issues/7917).

```
/data/github/current/vendor/gems/2.1.0/ruby/2.1.0/gems/scrolls-0.3.5/lib/scrolls/atomic.rb:22:in `synchronize': can't be called from trap context (ThreadError)
    from /data/github/current/vendor/gems/2.1.0/ruby/2.1.0/gems/scrolls-0.3.5/lib/scrolls/atomic.rb:22:in `get'
    from /data/github/current/vendor/gems/2.1.0/ruby/2.1.0/gems/scrolls-0.3.5/lib/scrolls/atomic.rb:46:in `value'
    from /data/github/current/vendor/gems/2.1.0/ruby/2.1.0/gems/scrolls-0.3.5/lib/scrolls/log.rb:176:in `get_global_context'
    from /data/github/current/vendor/gems/2.1.0/ruby/2.1.0/gems/scrolls-0.3.5/lib/scrolls/log.rb:96:in `log'
    from /data/github/current/vendor/gems/2.1.0/ruby/2.1.0/gems/scrolls-0.3.5/lib/scrolls.rb:54:in `log'
...
```

**Comment by asenchi** [comment]
Should no longer be an issue after https://github.com/asenchi/scrolls/pull/71
